(* Write a program that outputs the string representation of numbers from 1 to n. *)
(*  *)
(* But for multiples of three it should output “Fizz” instead of the number and for the multiples of five output “Buzz”. For numbers which are multiples of both three and five output “FizzBuzz”. *)
(*  *)
(* Example: *)
(*  *)
(* n = 15, *)
(*  *)
(* Return: *)
(* [ *)
(*     "1", *)
(*     "2", *)
(*     "Fizz", *)
(*     "4", *)
(*     "Buzz", *)
(*     "Fizz", *)
(*     "7", *)
(*     "8", *)
(*     "Fizz", *)
(*     "Buzz", *)
(*     "11", *)
(*     "Fizz", *)
(*     "13", *)
(*     "14", *)
(*     "FizzBuzz" *)
(*   ] *)
(*  *)

let fizz_buzz n =
  List.map (fun x -> if x mod 3 = 0 && x mod 5 = 0 then "FizzBuzz" else if x mod 3 = 0 then "fizz" else if x mod 5 = 0 then "buzz" else string_of_int x) (List.init n (fun x -> x + 1))
